- name: restart patroni
  become: true
  systemd:
    name: "{{ patroni_cluster_name }}"
    state: reloaded

- name: reload pgbouncer
  become: true
  systemd:
    name: pgbouncer
    state: reloaded